# Generated by Django 4.2.3 on 2023-07-07 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought_price', models.FloatField()),
                ('payment_method', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=7)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enrollments',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_gateway_id', models.CharField(max_length=255)),
                ('gateway', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
                ('user_email', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(max_length=255)),
                ('json_response', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.enrollment')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
