# Generated by Django 4.2.3 on 2023-07-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
