# Generated by Django 4.2.3 on 2023-07-23 07:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_enrollment_expiration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='classes_id',
            new_name='classes',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='bought_price',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='enrollment_id',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment',
            field=models.ForeignKey(
                default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.payments'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payments',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), (
                'attempted', 'Authorized/Failed'), ('paid', 'Captured')], default='created', max_length=10),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2024, 7, 22)),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='currency',
            field=models.CharField(default='INR', max_length=255),
        ),
        migrations.AlterField(
            model_name='payments',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
