# Generated by Django 4.2.3 on 2023-07-26 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_classes_enrollment_standard_payments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='order_gateway_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2024, 7, 25)),
        ),
        migrations.AlterField(
            model_name='payments',
            name='method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_gateway_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
