# Generated by Django 4.2.3 on 2023-07-25 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_classes_enrollment_standard_payments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2024, 7, 25)),
        ),
    ]
