# Generated by Django 4.2.3 on 2023-07-28 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_enrollment_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2024, 7, 28)),
        ),
    ]
