# Generated by Django 4.2.3 on 2023-10-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(
                blank=True, null=True, upload_to='uploads/profile_pics'),
        ),
    ]
