# Generated by Django 4.2.3 on 2024-01-20 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_merge_20231012_1506'),
        ('accounts', '0018_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='standard',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.classes'),
        ),
    ]
