# Generated by Django 4.2.10 on 2024-04-11 15:49

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_phoneperesponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralDetails',
            fields=[
                ('referral_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234', length=16, max_length=40, prefix='id_', primary_key=True, serialize=False)),
                ('referral_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.referraldetails'),
        ),
    ]
