# Generated by Django 4.2.3 on 2023-07-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('collectionid', models.CharField(blank=True, db_column='collectionId', max_length=255, null=True)),
                ('course_id', models.CharField(max_length=26)),
                ('user_id', models.CharField(max_length=26)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chapters',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('image', models.CharField(max_length=255)),
                ('latest_price', models.FloatField()),
                ('before_price', models.FloatField(blank=True, null=True)),
                ('public', models.IntegerField()),
                ('publish_at', models.DateTimeField()),
                ('user_id', models.CharField(max_length=26)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought_price', models.FloatField()),
                ('payment_method', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=7)),
                ('user_id', models.CharField(max_length=26)),
                ('course_id', models.CharField(max_length=26)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'enrollments',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('thumb_url', models.CharField(blank=True, max_length=255, null=True)),
                ('public', models.IntegerField()),
                ('position', models.IntegerField()),
                ('lesson_type', models.CharField(db_column='type', max_length=8)),
                ('status', models.CharField(max_length=10)),
                ('platform', models.CharField(blank=True, max_length=11, null=True)),
                ('platform_video_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.CharField(max_length=26)),
                ('chapter_id', models.CharField(blank=True, max_length=26, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lessons',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_gateway_id', models.CharField(max_length=255)),
                ('gateway', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
                ('user_email', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(max_length=255)),
                ('json_response', models.TextField()),
                ('enrollment_id', models.CharField(blank=True, max_length=26, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
