from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import *

app_name = 'courses'

urlpatterns = [
    path('classes/', login_required(ClassesView.as_view()), name='classes'),
    path("classes/<int:pk>/", login_required(ClassesUpdateView.as_view()),
         name="class-update"),
    path("classes/<int:pk>/delete/",
         login_required(ClassesDeleteView.as_view()), name="class-delete"),
    path('subjects/',  login_required(SubjectsView.as_view()), name='subjects'),
    path("subject/<int:pk>/", login_required(SubjectUpdateView.as_view()),
         name="subject-update"),
    path("subject/<int:pk>/delete/",
         login_required(SubjectDeleteView.as_view()), name="subject-delete"),
    path('chapters/',  login_required(ChapterView.as_view()), name='chapters'),
    path("chapter/<int:pk>/", login_required(ChapterUpdateView.as_view()),
         name="chapter-update"),
    path("chapter/<int:pk>/delete/",
         login_required(ChapterDeleteView.as_view()), name="chapter-delete"),
    path('lessons/',  login_required(LessonView.as_view()), name='lessons'),
    path("lesson/<int:pk>/", login_required(LessonUpdateView.as_view()),
         name="lesson-update"),
    path("lesson/<int:pk>/detail/",
         login_required(LessonDetailView.as_view()), name="lesson-detail"),
    path("lesson/<int:pk>/delete/",
         login_required(LessonDeleteView.as_view()), name="lesson-delete"),
    path('categories/', login_required(CategoriesView.as_view()), name='categories'),
    path("categories/<int:pk>/",
         login_required(CategoriesUpdateView.as_view()), name="category-update"),
    path("categories/<int:pk>/delete/",
         login_required(CategoriesDeleteView.as_view()), name="category-delete"),
    path('quizzes/', login_required(QuizView.as_view()), name='quizzes'),
    path("quizzes/<int:pk>/",
         login_required(QuizUpdateView.as_view()), name="quiz-update"),
    path("quizzes/<int:pk>/delete/",
         login_required(QuizDeleteView.as_view()), name="quiz-delete"),
    path('questions/', login_required(QuestionView.as_view()), name='questions'),
    path("questions/<int:pk>/",
         login_required(QuestionUpdateView.as_view()), name="question-update"),
    path("questions/<int:pk>/delete/",
         login_required(QuestionDeleteView.as_view()), name="question-delete"),
    path('choices/', login_required(ChoiceView.as_view()), name='choices'),
    path("choices/<int:pk>/",
         login_required(ChoiceUpdateView.as_view()), name="choice-update"),
    path("choices/<int:pk>/delete/",
         login_required(ChoiceDeleteView.as_view()), name="choice-delete"),
]
