# Generated by Django 4.2.3 on 2023-07-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_chapter_image_alter_classes_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='publish_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
