# Generated by Django 4.2.3 on 2023-07-11 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_lesson_description_alter_lesson_lesson_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='user',
            new_name='created_by',
        ),
    ]
