# Generated by Django 4.2.3 on 2023-07-21 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_category_subject_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='course',
            new_name='subject',
        ),
    ]
