# Generated by Django 4.2.3 on 2023-07-21 08:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_rename_course_chapter_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='before_price',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='classes',
            name='latest_price',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
