# Generated by Django 4.2.3 on 2023-08-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_alter_lesson_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('None', '---------'), ('video', 'Video'), ('document', 'Document'), ('image', 'Image'), ('text', 'Text'), ('quiz', 'Quiz')], db_column='type', default=None, max_length=8),
        ),
    ]
