# Generated by Django 4.2.3 on 2023-08-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assigment_file',
            field=models.FileField(blank=True, null=True, upload_to='media/uploads/assignments'),
        ),
    ]
