# Generated by Django 4.2.3 on 2023-08-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_alter_assignmentsubmission_solution_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
