# Generated by Django 4.2.3 on 2023-08-10 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_assignmentsubmission_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='marks',
            field=models.IntegerField(blank=True, null=True,validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
