# Generated by Django 4.2.3 on 2023-09-02 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_assignment_chapter_grades_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.assignment'),
        ),
    ]
