# Generated by Django 4.2.3 on 2023-09-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_lesson_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('None', '---------'), ('video', 'Video'), ('document', 'Document'), ('image', 'Image'),
                                   ('text', 'Text'), ('quiz', 'Quiz'), ('assignment', 'Assignment')], db_column='type', default=None, max_length=12),
        ),
    ]
