# Generated by Django 4.2.3 on 2023-09-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='due_date',
        ),
        migrations.AddField(
            model_name='assignment',
            name='time_required',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
