# Generated by Django 4.2.3 on 2023-10-19 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_alter_assignment_time_required'),
        ('courses', '0032_lesson_progress'),
    ]

    operations = [
    ]
