# Generated by Django 4.2.7 on 2024-04-03 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_alter_grades_grade'),
        ('courses', '0034_quizhash_question_lesson_quizhashquestionanswer'),
    ]

    operations = [
    ]
