# Generated by Django 4.2.10 on 2024-05-07 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_notes'),
        ('courses', '0039_quizhash_current_grade_and_more'),
    ]

    operations = [
    ]
