# Generated by Django 4.2.7 on 2024-05-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_merge_0039_notes_0039_quizhash_current_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('None', '---------'), ('video', 'Video'), ('document', 'Document'), ('quiz', 'Quiz'), ('assignment', 'Assignment')], db_column='type', default=None, max_length=12),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='platform',
            field=models.CharField(blank=True, choices=[('file', 'File')], default=None, max_length=11, null=True),
        ),
    ]
