# Generated by Django 4.2.11 on 2024-05-29 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_remove_lesson_quiz_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='chapter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.chapter'),
        ),
    ]
